version: "3.9"
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    working_dir: /usr/src/app
    entrypoint: python main.py
    volumes:
      - .:/usr/src/app